repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.4.0
      hooks:
          - id: check-merge-conflict
          - id: check-added-large-files
          - id: check-ast
          - id: check-symlinks
          - id: trailing-whitespace
          - id: debug-statements
          - id: check-toml
          - id: check-yaml
    - repo: https://github.com/charliermarsh/ruff-pre-commit
      rev: v0.0.272
      hooks:
          - id: ruff
            args:
              - --fix
    - repo: https://github.com/psf/black
      rev: 23.3.0
      hooks:
          - id: black
            args: ["--target-version", "py310"]
    - repo: https://github.com/asottile/pyupgrade
      rev: v3.4.0
      hooks:
          - id: pyupgrade
            args: [--py37-plus]
